export const HOTELS = [
  {
    id: "jamaica-inn",
    name: "Jamaica Inn",
    location: "Ocho Rios",
    googleMapsUrl: "https://maps.google.com/?q=Jamaica+Inn+Ocho+Rios+Jamaica",
    website: "https://www.jamaicainn.com",
    instagram: "https://www.instagram.com/jamaicainnhotel/",
    marchPrice: 380,
    priceTier: 3,
    seclusion: 4,
    activity: 2,
    romance: 4,
    amenities: ["Private Beach", "Oceanfront Dining", "Spa Services", "Water Sports"],
    description:
      "Old-world elegance on a quiet crescent bay with polished service and a slow, restorative pace.",
    photos: [
      "assets/hotels/Jamaican%20Inn/beach_birdseye.jpg",
      "assets/hotels/Jamaican%20Inn/de1a1744.jpg",
      "assets/hotels/Jamaican%20Inn/de1a0074.jpg",
      "assets/hotels/Jamaican%20Inn/de1a2346.jpg",
      "assets/hotels/Jamaican%20Inn/de1a2453.jpg",
      "assets/hotels/Jamaican%20Inn/de1a3160.jpg",
      "assets/hotels/Jamaican%20Inn/de1a3635.jpg",
      "assets/hotels/Jamaican%20Inn/jamaica-inn-nl19-16.jpg",
      "assets/hotels/Jamaican%20Inn/jamaica-inn-nl19-18.jpg",
      "assets/hotels/Jamaican%20Inn/jamaica-inn-nl19-22.jpg",
      "assets/hotels/Jamaican%20Inn/jamaica-inn-nl22s-25a.jpg",
      "assets/hotels/Jamaican%20Inn/jamaica-inn-nl22s-40.jpg",
      "assets/hotels/Jamaican%20Inn/living-are-cottage-6.jpg",
      "assets/hotels/Jamaican%20Inn/master-bedroom-view-cottage-6.jpg",
      "assets/hotels/Jamaican%20Inn/teddy-s-grill.jpg",
    ],
  },
  {
    id: "goldeneye",
    name: "GoldenEye",
    location: "Oracabessa",
    googleMapsUrl: "https://maps.google.com/?q=GoldenEye+Oracabessa+Jamaica",
    website: "https://www.goldeneye.com",
    instagram: "https://www.instagram.com/goldeneye/",
    marchPrice: 650,
    priceTier: 4,
    seclusion: 5,
    activity: 3,
    romance: 5,
    amenities: ["Lagoon Villas", "Snorkeling", "Kayaks", "Farm-to-Table Dining"],
    description:
      "A lush, cinematic hideaway of coves, lagoons, and modern island design tied to Bond-era mythology.",
    photos: [
      "assets/hotels/Goldeneye/11-lagoon-cottages-1600x1188.jpg",
      "assets/hotels/Goldeneye/12-lagoon-cottages-carousel-1.jpg",
      "assets/hotels/Goldeneye/12-lagoon-cottages-carousel-2.jpg",
      "assets/hotels/Goldeneye/12-lagoon-cottages-carousel-3.jpg",
      "assets/hotels/Goldeneye/15-one-bedroom-hut-dune-carousel-2.jpg",
    ],
  },
  {
    id: "rockhouse",
    name: "Rockhouse",
    location: "Negril",
    googleMapsUrl: "https://maps.google.com/?q=Rockhouse+Negril+Jamaica",
    website: "https://www.rockhouse.com",
    instagram: "https://www.instagram.com/rockhousehotel/",
    marchPrice: 275,
    priceTier: 2,
    seclusion: 4,
    activity: 2,
    romance: 4,
    amenities: ["Cliffside Cottages", "Infinity Pool", "Yoga Pavilion", "Sunset Bar"],
    description:
      "Iconic Negril cliff views, soulful design, and laid-back luxury rooted in Jamaican craft and character.",
    photos: [
      "assets/hotels/Rockhouse/52587178001_f6515fb446_k.jpg",
      "assets/hotels/Rockhouse/52587392706_4d0020a1fd_c%20%281%29%20%281%29.webp",
      "assets/hotels/Rockhouse/54764276212_6b524d458a_c.webp",
      "assets/hotels/Rockhouse/54765471050_85560056c4_k.jpg",
      "assets/hotels/Rockhouse/Rockhouse%20Restaurant.png",
      "assets/hotels/Rockhouse/image%20%2810%29.webp",
      "assets/hotels/Rockhouse/image%20%2811%29.webp",
      "assets/hotels/Rockhouse/image%20%2812%29.webp",
      "assets/hotels/Rockhouse/image%20%289%29.webp",
      "assets/hotels/Rockhouse/image_-_2025-07-24T000532.550_1753304759302_4733f24f05df.webp",
      "assets/hotels/Rockhouse/sit-back-and-relax_1750636774204_7646bef18c4c.webp",
    ],
  },
  {
    id: "san-souci",
    name: "San Souci",
    location: "Ocho Rios",
    googleMapsUrl: "https://maps.google.com/?q=Couples+Sans+Souci+Ocho+Rios+Jamaica",
    website: "https://couples.com/resorts/sans-souci",
    instagram: "https://www.instagram.com/couplesresorts/",
    marchPrice: 290,
    priceTier: 2,
    seclusion: 3,
    activity: 3,
    romance: 3,
    amenities: ["Adults-Only", "All-Inclusive", "Mineral Grotto", "Scuba Included", "All-Inclusive Dining"],
    description:
      "An adults-only hillside escape with tropical gardens and all-inclusive ease near Ocho Rios.",
    photos: [
      "assets/hotels/SANSOUCI/couplesresorts-sanssouci-03-gallery-7-67b4bbeaa9528.webp",
      "assets/hotels/SANSOUCI/couplesresorts-sanssouci-03-gallery-6-67b4bbe87b26d.webp",
      "assets/hotels/SANSOUCI/couplesresorts-sanssouci-03-gallery-1-67b4bbdd84771.webp",
      "assets/hotels/SANSOUCI/couplesresorts-sanssouci-03-gallery-15-67b4bbfbe253b.webp",
      "assets/hotels/SANSOUCI/couplesresorts-sanssouci-03-gallery-16-67b4bbfe6d2fc.webp",
      "assets/hotels/SANSOUCI/couplesresorts-sanssouci-03-gallery-20-67b4bc075d7fd.webp",
    ],
  },
  {
    id: "excellence-oyster-bay",
    name: "Excellence Oyster Bay",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Excellence+Oyster+Bay+Jamaica",
    website: "https://www.excellenceresorts.com/montego-bay/excellence-oyster-bay/",
    instagram: "https://www.instagram.com/excellenceresorts/",
    marchPrice: 520,
    priceTier: 4,
    seclusion: 3,
    activity: 4,
    romance: 5,
    amenities: ["Adults-Only", "All-Inclusive", "Private Peninsula", "Butler Suites", "World-Class Spa"],
    description:
      "Contemporary adults-only luxury on a private peninsula with elevated food, spa, and suite categories.",
    photos: [
      "assets/hotels/Excellence/excellence.jpg",
      "assets/hotels/Excellence/excellence2.jpg",
      "assets/hotels/Excellence/excellence3.jpg",
      "assets/hotels/Excellence/excellence4.jpg",
      "assets/hotels/Excellence/excellence5.jpg",
      "assets/hotels/Excellence/excellence6.jpg",
      "assets/hotels/Excellence/excellence7.jpg",
    ],
  },
  {
    id: "the-cliff-hotel",
    name: "The Cliff Hotel",
    location: "Negril",
    googleMapsUrl: "https://maps.google.com/?q=The+Cliff+Hotel+Negril+Jamaica",
    website: "https://www.thecliffjamaica.com",
    instagram: "https://www.instagram.com/thecliffjamaica/",
    marchPrice: 320,
    priceTier: 3,
    seclusion: 4,
    activity: 2,
    romance: 5,
    amenities: ["Clifftop Pool", "Fine Dining", "Boutique Spa", "Ocean View Suites"],
    description:
      "A refined boutique retreat with dramatic cliff edges, moody sunsets, and intimate service.",
    photos: [
      "assets/hotels/The%20Cliff%20Hotel/1759448075978-uyf28r.jpg",
      "assets/hotels/The%20Cliff%20Hotel/1759511463575-ojgi64.jpg",
      "assets/hotels/The%20Cliff%20Hotel/1759511707097-x3xu5u.jpg",
      "assets/hotels/The%20Cliff%20Hotel/1759511907850-qk18of.jpg",
      "assets/hotels/The%20Cliff%20Hotel/1759511908128-yhlwq6.jpg",
      "assets/hotels/The%20Cliff%20Hotel/1759511908439-b7r94a.jpg",
    ],
  },
  {
    id: "azul",
    name: "Azul Beach Resort Negril",
    location: "Negril",
    googleMapsUrl: "https://maps.google.com/?q=Azul+Beach+Resort+Negril+by+Karisma+Jamaica",
    website: "https://www.karismahotels.com/azul-beach-resorts/negril",
    instagram: "https://www.instagram.com/azulbeachresorts/",
    marchPrice: 350,
    priceTier: 3,
    seclusion: 4,
    activity: 3,
    romance: 4,
    amenities: ["Swim-Up Suites", "All-Inclusive", "Gourmet Inclusive", "Beach Butler", "Family + Adult Zones"],
    description:
      "A polished all-inclusive with modern rooms, long beachfront, and flexible options for groups or couples.",
    photos: [
      "assets/hotels/Azul/azul-beach-negril-drone.jpg",
      "assets/hotels/Azul/azul_beach_resort_negril_pool-1030x688.jpg",
      "assets/hotels/Azul/lifestyle-beach-9.webp",
      "assets/hotels/Azul/lifestyle_rooms_azul_beach_negril_2.webp",
      "assets/hotels/Azul/tamarindo_pool_bar_restaurants_and_bars_azul_beach_negril_2.webp",
      "assets/hotels/Azul/3328ee79.avif",
      "assets/hotels/Azul/3328ee79-1.avif",
    ],
  },
  {
    id: "secrets",
    name: "Secrets Wild Orchid Montego Bay",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Secrets+Wild+Orchid+Montego+Bay+Jamaica",
    website:
      "https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/jamaica/wild-orchid-montego-bay/",
    instagram: "https://www.instagram.com/secretsresorts/",
    marchPrice: 480,
    priceTier: 4,
    seclusion: 2,
    activity: 4,
    romance: 5,
    amenities: ["Adults-Only", "All-Inclusive", "Nightlife", "Oceanfront Suites"],
    description:
      "An adults-only all-inclusive with strong nightlife, social energy, and easy airport proximity.",
    photos: [
      "assets/hotels/secrets/2022-02-09.webp",
      "assets/hotels/secrets/2025-12-16.webp",
      "assets/hotels/secrets/SESMB-JR-OF-1A-RGB-CB.webp",
      "assets/hotels/secrets/SESMB-Rafting-on-the-Martha-Brae-CP.webp",
      "assets/hotels/secrets/SESMB-SPA-Circuit-3-CB.webp",
      "assets/hotels/secrets/unnamed.webp",
      "assets/hotels/secrets/unnamed-1.webp",
    ],
  },
  {
    id: "rose-hall",
    name: "Iberostar Waves Rose Hall Beach",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Iberostar+Waves+Rose+Hall+Beach+Montego+Bay+Jamaica",
    website: "https://www.iberostar.com/en/hotels/montego-bay/iberostar-waves-rose-hall-beach/",
    instagram: "https://www.instagram.com/iberostar/",
    marchPrice: 400,
    priceTier: 3,
    seclusion: 2,
    activity: 5,
    romance: 3,
    amenities: ["Large Pool Complex", "Live Entertainment", "Beachfront Access", "Family Rooms"],
    description:
      "An energetic Montego Bay resort base with easy beach access and lots of daytime activity.",
    photos: [
      "assets/hotels/Rose%20Hall/image.avif",
      "assets/hotels/Rose%20Hall/rose-hall-1.png",
      "assets/hotels/Rose%20Hall/rose-hall-2.png",
      "assets/hotels/Rose%20Hall/rose-hall-3.png",
    ],
  },
];
