export const HOTELS = [
  {
    id: "jamaica-inn",
    name: "Jamaica Inn",
    location: "Ocho Rios",
    googleMapsUrl: "https://maps.google.com/?q=Jamaica+Inn+Ocho+Rios+Jamaica",
    website: "https://www.jamaicainn.com",
    marchPrice: 380,
    priceTier: 3,
    seclusion: 4,
    activity: 2,
    romance: 4,
    amenities: ["Private Beach", "Oceanfront Dining", "Spa Services", "Water Sports"],
    description:
      "Old-world elegance on a quiet crescent bay with polished service and a slow, restorative pace.",
    photos: ["assets/hotels/jamaica-inn-1.svg", "assets/hotels/jamaica-inn-2.svg"],
  },
  {
    id: "half-moon",
    name: "Half Moon",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Half+Moon+Montego+Bay+Jamaica",
    website: "https://www.halfmoon.com",
    marchPrice: 450,
    priceTier: 4,
    seclusion: 3,
    activity: 4,
    romance: 4,
    amenities: ["Golf Course", "Equestrian Centre", "Private Villas", "Wellness Spa"],
    description:
      "A classic Caribbean estate with broad beachfront, family-friendly options, and polished resort amenities.",
    photos: ["assets/hotels/half-moon-1.svg", "assets/hotels/half-moon-2.svg"],
  },
  {
    id: "goldeneye",
    name: "GoldenEye",
    location: "Oracabessa",
    googleMapsUrl: "https://maps.google.com/?q=GoldenEye+Oracabessa+Jamaica",
    website: "https://www.goldeneye.com",
    marchPrice: 650,
    priceTier: 4,
    seclusion: 5,
    activity: 3,
    romance: 5,
    amenities: ["Lagoon Villas", "Snorkeling", "Kayaks", "Farm-to-Table Dining"],
    description:
      "A lush, cinematic hideaway of coves, lagoons, and modern island design tied to Bond-era mythology.",
    photos: ["assets/hotels/goldeneye-1.svg", "assets/hotels/goldeneye-2.svg"],
  },
  {
    id: "rockhouse",
    name: "Rockhouse",
    location: "Negril",
    googleMapsUrl: "https://maps.google.com/?q=Rockhouse+Negril+Jamaica",
    website: "https://www.rockhouse.com",
    marchPrice: 275,
    priceTier: 2,
    seclusion: 4,
    activity: 2,
    romance: 4,
    amenities: ["Cliffside Cottages", "Infinity Pool", "Yoga Pavilion", "Sunset Bar"],
    description:
      "Iconic Negril cliff views, soulful design, and laid-back luxury rooted in Jamaican craft and character.",
    photos: ["assets/hotels/rockhouse-1.svg", "assets/hotels/rockhouse-2.svg"],
  },
  {
    id: "the-cliff-hotel",
    name: "The Cliff Hotel",
    location: "Negril",
    googleMapsUrl: "https://maps.google.com/?q=The+Cliff+Hotel+Negril+Jamaica",
    website: "https://www.thecliffjamaica.com",
    marchPrice: 320,
    priceTier: 3,
    seclusion: 4,
    activity: 2,
    romance: 5,
    amenities: ["Clifftop Pool", "Fine Dining", "Boutique Spa", "Ocean View Suites"],
    description:
      "A refined boutique retreat with dramatic cliff edges, moody sunsets, and intimate service.",
    photos: ["assets/hotels/the-cliff-hotel-1.svg", "assets/hotels/the-cliff-hotel-2.svg"],
  },
  {
    id: "san-souci",
    name: "San Souci",
    location: "Ocho Rios",
    googleMapsUrl: "https://maps.google.com/?q=Couples+Sans+Souci+Ocho+Rios+Jamaica",
    website: "https://couples.com/resorts/sans-souci",
    marchPrice: 290,
    priceTier: 2,
    seclusion: 3,
    activity: 3,
    romance: 3,
    amenities: ["Adults-Only", "Mineral Grotto", "Scuba Included", "All-Inclusive Dining"],
    description:
      "An adults-only hillside escape with tropical gardens and all-inclusive ease near Ocho Rios.",
    photos: ["assets/hotels/san-souci-1.svg", "assets/hotels/san-souci-2.svg"],
  },
  {
    id: "rose-hall",
    name: "Rose Hall",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Rose+Hall+Montego+Bay+Jamaica",
    website: "https://www.iberostar.com/en/hotels/montego-bay/iberostar-rose-hall-beach/",
    marchPrice: 400,
    priceTier: 3,
    seclusion: 2,
    activity: 5,
    romance: 3,
    amenities: ["Large Pool Complex", "Live Entertainment", "Beachfront Access", "Family Rooms"],
    description:
      "An energetic Montego Bay resort base with easy beach access and lots of daytime activity.",
    photos: ["assets/hotels/rose-hall-1.svg", "assets/hotels/rose-hall-2.svg"],
  },
  {
    id: "azul",
    name: "Azul",
    location: "Negril",
    googleMapsUrl: "https://maps.google.com/?q=Azul+Beach+Resort+Negril+Jamaica",
    website: "https://www.karismahotels.com/azul-beach-resorts",
    marchPrice: 350,
    priceTier: 3,
    seclusion: 4,
    activity: 3,
    romance: 4,
    amenities: ["Swim-Up Suites", "Gourmet Inclusive", "Beach Butler", "Family + Adult Zones"],
    description:
      "A polished all-inclusive with modern rooms, long beachfront, and flexible options for groups or couples.",
    photos: ["assets/hotels/azul-1.svg", "assets/hotels/azul-2.svg"],
  },
  {
    id: "excellence-oyster-bay",
    name: "Excellence Oyster Bay",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Excellence+Oyster+Bay+Jamaica",
    website: "https://www.excellenceresorts.com/montego-bay/excellence-oyster-bay/",
    marchPrice: 520,
    priceTier: 4,
    seclusion: 3,
    activity: 4,
    romance: 5,
    amenities: ["Adults-Only", "Private Peninsula", "Butler Suites", "World-Class Spa"],
    description:
      "Contemporary adults-only luxury on a private peninsula with elevated food, spa, and suite categories.",
    photos: [
      "assets/hotels/excellence-oyster-bay-1.svg",
      "assets/hotels/excellence-oyster-bay-2.svg",
    ],
  },
  {
    id: "secrets",
    name: "Secrets",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Secrets+Montego+Bay+Jamaica",
    website: "https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/jamaica/",
    marchPrice: 480,
    priceTier: 4,
    seclusion: 2,
    activity: 4,
    romance: 5,
    amenities: ["Adults-Only", "All-Inclusive", "Nightlife", "Oceanfront Suites"],
    description:
      "An adults-only all-inclusive with strong nightlife, social energy, and easy airport proximity.",
    photos: ["assets/hotels/secrets-1.svg", "assets/hotels/secrets-2.svg"],
  },
  {
    id: "sandals",
    name: "Sandals",
    location: "Montego Bay",
    googleMapsUrl: "https://maps.google.com/?q=Sandals+Montego+Bay+Jamaica",
    website: "https://www.sandals.com/montego-bay/",
    marchPrice: 600,
    priceTier: 4,
    seclusion: 2,
    activity: 5,
    romance: 5,
    amenities: ["All-Inclusive", "Overwater Bar", "Scuba Included", "Couples Packages"],
    description:
      "The flagship couples-focused all-inclusive with strong activity programming and upscale inclusions.",
    photos: ["assets/hotels/sandals-1.svg", "assets/hotels/sandals-2.svg"],
  },
];
